# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40bde03bddd4907f0e2f21e2f3af16c1b5a650828a915799ac429df2665e8dda0b2bde9e539af8a14aa482b5c324eebb7c8a0836b067b6d48806ecbd8841799f

test:
  secret_key_base: 2feb1a1c25e8179cf294b7a8b63c651fcc2657e68c81cddcdc716901b1a4d40ab7bd1003a697b3defcc29277dd3a2322ddf745741f2ef20c752ce179078c7d22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
